"""empty message

Revision ID: 9e1f4438089c
Revises: 
Create Date: 2025-06-16 23:51:04.094832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1f4438089c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('duracion_predeterminada', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('auth_dos_factores', sa.Boolean(), nullable=True),
    sa.Column('secreto_2fa', sa.String(length=32), nullable=True),
    sa.Column('cierre_sesion_auto', sa.Boolean(), nullable=True),
    sa.Column('tiempo_inactividad', sa.Integer(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notificaciones_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psicologos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=10), nullable=True),
    sa.Column('especialidad', sa.String(length=255), nullable=True),
    sa.Column('otra_especialidad', sa.String(length=100), nullable=True),
    sa.Column('numero_licencia', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion_consulta', sa.String(length=255), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('estado_verificacion', sa.String(length=20), nullable=True),
    sa.Column('institucion', sa.String(length=100), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('verificado_por', sa.Integer(), nullable=True),
    sa.Column('comentarios_verificacion', sa.Text(), nullable=True),
    sa.Column('ruta_archivo_titulo', sa.String(length=255), nullable=True),
    sa.Column('ruta_archivo_licencia', sa.String(length=255), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['verificado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notificaciones_email', sa.Boolean(), nullable=True),
    sa.Column('tiempo_anticipacion', sa.Integer(), nullable=True),
    sa.Column('frecuencia_recordatorios', sa.Integer(), nullable=True),
    sa.Column('alertas_cambios_citas', sa.Boolean(), nullable=True),
    sa.Column('alertas_pacientes_nuevos', sa.Boolean(), nullable=True),
    sa.Column('notificaciones_actualizacion', sa.Boolean(), nullable=True),
    sa.Column('sonidos_notificacion', sa.Boolean(), nullable=True),
    sa.Column('retencion_datos', sa.Integer(), nullable=True),
    sa.Column('recordatorios_automaticos', sa.Boolean(), nullable=True),
    sa.Column('psicologo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('asunto', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('respondido', sa.Boolean(), nullable=True),
    sa.Column('ip_remitente', sa.String(length=50), nullable=True),
    sa.Column('psicologo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ocupacion', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('diagnostico', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('psicologo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psicologo_tipo_cita',
    sa.Column('psicologo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_cita_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id'], ),
    sa.ForeignKeyConstraint(['tipo_cita_id'], ['tipos_cita.id'], ),
    sa.PrimaryKeyConstraint('psicologo_id', 'tipo_cita_id')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo_cita_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('asistio', sa.Boolean(), nullable=True),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('psicologo_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id'], ),
    sa.ForeignKeyConstraint(['tipo_cita_id'], ['tipos_cita.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('psicologo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['psicologo_id'], ['psicologos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('tiempo_envio', sa.DateTime(), nullable=False),
    sa.Column('enviada', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('destinatario', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificaciones')
    op.drop_table('notas')
    op.drop_table('citas')
    op.drop_table('psicologo_tipo_cita')
    op.drop_table('pacientes')
    op.drop_table('contactos')
    op.drop_table('configuraciones')
    op.drop_table('psicologos')
    op.drop_table('notificaciones_sistema')
    op.drop_table('usuarios')
    op.drop_table('tipos_cita')
    op.drop_table('roles')
    # ### end Alembic commands ###
