"""Add notas column to citas table

Revision ID: b9d337c7edc0
Revises: 9e1f4438089c
Create Date: 2025-06-23 00:53:22.432960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d337c7edc0'
down_revision = '9e1f4438089c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_column('notas')

    # ### end Alembic commands ###
